#spring.cloud.stream.binders.configuration

#logging.level.root = DEBUG

spring.cloud.stream.kafka.binder.configuration.commit.interval.ms = 1000
spring.cloud.stream.kafka.binder.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.cloud.stream.kafka.binder.configuration.value.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.binder.configuration.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.binder.configuration.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.binder.min-partition-count=1
spring.cloud.stream.kafka.binder.replication-factor=1

spring.cloud.function.definition=generator;externalRefererPage;externalRefererSplitter;aggregator;printer
#  ;aggregator;printer;externalRefererPage;

spring.cloud.stream.bindings.generator-out-0.destination=page-views


#
spring.cloud.stream.bindings.externalRefererPage-in-0.destination=page-views
spring.cloud.stream.bindings.externalRefererPage-out-0.destination=referred-page



spring.cloud.stream.bindings.externalRefererSplitter-in-0.destination=page-views
spring.cloud.stream.bindings.externalRefererSplitter-out-0.destination=referred-page-views
spring.cloud.stream.bindings.externalRefererSplitter-out-1.destination=internal-page-views


spring.cloud.stream.bindings.aggregator-in-0.destination=page-views
spring.cloud.stream.bindings.aggregator-out-0.destination=page-views-counts

spring.cloud.stream.bindings.printer-in-0.destination=page-views-counts

#spring.cloud.stream.bindings.wordcount-in-0.destination=fb-message
#spring.cloud.stream.bindings.wordcount-out-0.destination=word-counts-english
#spring.cloud.stream.bindings.wordcount-out-1.destination=word-counts-french
#spring.cloud.stream.bindings.wordcount-out-2.destination=word-counts-spanish
#spring.cloud.stream.kafka.streams.bindings.wordcount-out-0.producer.key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#spring.cloud.stream.kafka.streams.bindings.wordcount-out-1.producer.key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#spring.cloud.stream.kafka.streams.bindings.wordcount-out-2.producer.key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#spring.cloud.stream.kafka.streams.bindings.wordcount-out-0.producer.value-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#spring.cloud.stream.kafka.streams.bindings.wordcount-out-1.producer.value-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#spring.cloud.stream.kafka.streams.bindings.wordcount-out-2.producer.value-serde=org.apache.kafka.common.serialization.Serdes$StringSerde


#spring.cloud.stream.bindings.pvout.destination=pvs
#spring.cloud.stream.bindings.pvout.producer.header-mode=none
#
#spring.cloud.stream.bindings.pvin.destination=pvs
#spring.cloud.stream.bindings.pvin.consumer.header-mode=none
#
#spring.cloud.stream.bindings.pcout.destination=pcs
#spring.cloud.stream.bindings.pcout.producer.use-native-encoding=true
#spring.cloud.stream.kafka.streams.bindings.pcout.producer.key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#spring.cloud.stream.kafka.streams.bindings.pcout.producer.value-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#
#
#spring.cloud.stream.bindings.pcin.destination=pcs
#spring.cloud.stream.bindings.pcin.consumer.use-native-decoding=true
#spring.cloud.stream.bindings.pcin.group=true
#spring.cloud.stream.bindings.pcin.consumer.header-mode=none
#spring.cloud.stream.bindings.pcin.content-type=application/json
#spring.cloud.stream.kafka.streams.bindings.pcin.consumer.key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#spring.cloud.stream.kafka.streams.bindings.pcin.consumer.value-serde=org.apache.kafka.common.serialization.Serdes$StringSerde

