@startuml
title Async Command over HTTP
hide footbox
'skinparam monochrome reverse
A->B++: POST /orders
A++

A<--B--:202 Accepted\norderId: 123
A--
loop
A-->A++: after a while
A->B++:GET /order/123
A<--B--: "pending"
A--
end
hnote over B: background work completed
A-->A++: after a while
A->B++:GET /order/123
A<--B: a) 200 OK {results}, or
A<--B--: b) 302 Redirect to download
@enduml