@startuml
title Commands vs Events
hide footbox
skinparam monochrome reverse

Checkout->Teleport: <<command>>\nPlaceOrder
Checkout<-Teleport: <<event>>\nOrderPlaced
Reminder<-Teleport: <<event>>\nOrderPlaced
@enduml