@startuml
title Duplicates by Producer
hide footbox

hnote over P: seq++
P->K: M{ik=seq+p.id}
K->
hnote over P: ⏱️
P->K: M{ik=seq+p.id}
hnote over K: ignore\nduplicate
@enduml
? ts
? uuid
? seq + p thread id