@startuml
title Duplicates detected via message id from broker
hide footbox
skinparam monochrome reverse

Rabbit->C: M1{id:7}
note over Cache: Redis\nDB
C->Cache: put id:7
Rabbit->C: M1{id:7}
C->Cache!!: put id:7
hnote over C: skip duplicate


@enduml
? inbox
? duplicates between Producer->Rabbit