@startuml
title Duplicates fixed via Client-generated IDs
hide footbox
skinparam monochrome reverse
'database DB

P->P: UUID1=new uuid
P->B: PlaceOrder{id=UUID1}
B->C: PlaceOrder{id=UUID1}
C->DB: insert Order(pk/uk=UUID1)
hnote over C: error
B->C: PlaceOrder{id=UUID1}
C->DB!!: insert Order(pk/uk=UUID1)
hnote over DB: PK violation
@enduml
? inbox
? duplicates between P->B