@startuml
title Duplicates
hide footbox
skinparam monochrome reverse

Inventory->B: ItemSold {q:1,newStock:11}
hnote over Catalog: stock 12
B->Catalog: ItemSold {q:1,newStock:11}
B->Catalog: ItemSold {q:1,newStock:11}
hnote over Catalog: stock 11
@enduml
? inbox
? duplicates between P->B