@startuml
title Duplicated Consume
hide footbox
skinparam monochrome reverse

P->B: M
B->C: M
hnote over C: ?
B->C: M
@enduml
? when does B re-send?
? idempotent/self-correcting M semantics
? producer-generated idempotency key
? inbox pattern