@startuml
title Producer Race\nFix: Send ObservedAt
hide footbox
actor Client
participant P1
participant P2

hnote over Client: a) sends initial time\nas request header

Client-[#green]>P1: <font color=green>Request1\ntime: 10:00
activate P1 #lightgreen
hnote over P1: b) samples time ASAP
P1-[#green]>Network: call (200ms)
activate Network #lightgreen
Client-[#blue]>P2: Request2\ntime: 10:01
activate P2 #lightblue
P2-[#blue]>Network:call (50ms)
activate Network #lightblue
P2<[#blue]--Network--
Topic<[#blue]-P2--: M2 {observedAt:10:01}
P1<--Network--
Topic<[#green]-P1--: M1 {observedAt:10:00}

@enduml

