@startuml
title Producer Race\nFix: Produce ASAP (before any network call)
hide footbox
participant Client
participant P1
participant P2
participant "Topic A\nPartition 7" as TA_P7
participant "Topic B\nPartition 5" as TB_P5 order 10

Client->P1++: Request1
TA_P7<-P1: M1 {key:7}
'Client<--P1--:202 Accepted
Client->P2++: Request2
P2->TA_P7: M2 {key:7}
P2--

== later ==
TA_P7->Processor++:M1
Processor->ExtAPI++:call (50ms)
Processor<--ExtAPI--
TB_P5<-Processor--:MFull1 {key:7}

TA_P7->Processor++:M2
Processor->ExtAPI++:call (200ms)
Processor<--ExtAPI--
TB_P5<-Processor--:MFull2 {key:7}
@enduml

