@startuml
title Consumer Out of Order\nFix via INBOX
hide footbox
database INBOX order 10
participant Poller order 11

->Consumer: M1:ActivateOffer{Nat5}\ntime: 11:00
Consumer->INBOX: INSERT M1
->Consumer: M2:AddCredit{5E}\ntime: 10:00
Consumer->INBOX: INSERT M2
hnote over Poller: every 1s
Poller->INBOX: SELECT from INBOX\nWHERE insert_time < 5s ago\nORDER by time asc\nLIMIT 1
Poller++
INBOX-->Poller: M2(time:10:00)
Poller->Poller++: process(M2)
Poller--
Poller--
Poller->INBOX: SELECT ..
Poller++
INBOX-->Poller: M1(time:10:01)
Poller->Poller++: process(M1)
Poller--
Poller--
@enduml
