@startuml
title Producer Race
hide footbox
queue B order 9
actor U

U->P1: Request1\ntime: 10:00
activate P1
U->P2: Request2\ntime: 10:00
activate P2
hnote over P1: takes\nlonger
P2->B: M2
deactivate P2
P1->B: M1
deactivate P1
@enduml
? receivedAt vs observedAt

