@startuml
title Producer Race
hide footbox
queue B order 9
actor U

U->P1: <<http>>\nRequest1\ntime: 7:00:00
activate P1
U->P2: <<http>>\nRequest2\ntime: 7:00:01
activate P2
hnote over P1: 3s
hnote over P2: 1s
P2->B: M2
deactivate P2
P1->B: M1
deactivate P1
@enduml
? receivedAt vs observedAt

