@startuml
title Consumer Out of Order
hide footbox

->Consumer!!: ActivateOffer{simId:7,offer:National5}\nObservedAt: 10:01
hnote over Consumer #FFAAAA: ERROR\ninsufficient\ncredit

->Consumer: AddCredit{simId:7,credit: 5 EUR}\nObservedAt: 10:00
@enduml
