@startuml
title Consumer Race
hide footbox
skinparam monochrome reverse
database DB order 10

P->B: M1{id:7,U1}
P->B: M2{id:7,U2}

B->C2: M1{id:7,U1}
B->C1: M2{id:7,U2}
C1->DB: U2
C2->DB!!: U1
hnote over DB: Update U1 fails when\napplied **AFTER** U2
@enduml
