@startuml
title Producer Race
hide footbox
skinparam monochrome reverse

LB->pod1: REST Req1\nSeq:x1
activate pod1
hnote over pod1: slow call of API/DB
LB->pod2: REST Req2\nSeq:x2
activate pod2
hnote over pod2: fast call of API/DB
pod2->B: M2{key=7,observedAt=x2}
deactivate pod2
pod1->B: M1{key=7,observedAt=x1}
deactivate pod1
@enduml
? receivedAt vs observedAt

