@startuml
title Producer Race
hide footbox
skinparam monochrome reverse
actor U

U->Tomcat1: REST Req1
activate Tomcat1
hnote over Tomcat1: slow call of API/DB
U->Tomcat2: REST Req2
activate Tomcat2
hnote over Tomcat2: fast call of API/DB
Tomcat2->B: M2
deactivate Tomcat2
Tomcat1->B: M1
deactivate Tomcat1
@enduml
? receivedAt vs observedAt

