@startuml
title Temporal Expectations should be controlled via message chains
hide footbox
skinparam monochrome reverse
participant P
participant "P"

P-->C: M

C-->P: MDoneEvent
hnote over "P": after event received
"P"->C: GET M\nExpecting done
@enduml
