@startuml
'title Consumer Callback Race
hide footbox

-> Producer++: <font color=green>add(5€)
Broker<-Producer--: <font color=green>1.CreditAdded {id}

->Producer++:<font color=blue>add(7€)
Broker<-Producer--: <font color=blue>2.CreditAdded {id}
Broker->Consumer++: <font color=green>1
Consumer->Producer++: <font color=green>GET credit/{id}   **//callback**
Consumer<--Producer--: <font color=blue>12€
hnote over Consumer #FFAAAA: huh?!

@enduml