@startuml
title Consumer Race
hide footbox

B->Consumer++: M1:AddCredit{5 EUR}
Consumer->Thread1++: process
Consumer--

B->Consumer++: M2:ActivateOffer{Nat5}
Consumer->Thread2++: process
hnote over Thread1,Thread2 #FFAAAA: overlap
Consumer--
@enduml
