@startuml
title Consumer Callback Race vs Produce DB Replication

-> A++:call
A -> A.PrimaryDB : UPDATE P
A.PrimaryDB --> A.ReadReplicaDB: UPDATE P (lagging)B
B<--A--: PUpdatedEvent

hnote over A.ReadReplicaDB: replica of a legacy DB
B ->A++: GET P
A->A.ReadReplicaDB: SELECT P (stale, 10s behind)
B<--A--: P (stale!)

@enduml