@startuml
'title Consumer Race
hide footbox
database DB order 9

hnote over DB: 0€
B->C1++: CreditAdded {simId:7,+5€}
B->C2++: CreditAdded {simId:7,+3€}
C1<-DB: 0€
C2<-DB: 0€
C1->DB: <font color=black>                                    0+5€
C1--
hnote over DB: 5€
C2->DB: <font color=red>                          0+3€
C2--
hnote over DB #FFAAAA: 3€

@enduml
