@startuml
'title Consumer Callback Race vs Produce DB Replication
hide footbox
participant Producer
participant DB
participant ReadDB

-> Producer++:update
Producer -> DB : UPDATE
'hnote over ReadDB #FFAAAA: large lag\nvs Primary
Consumer<--Producer--: UpdatedEvent {id}
Consumer++
Consumer->Producer++: GET /{id}      **// callback to source**
Producer->ReadDB: SELECT
Consumer<--Producer--: stale data
DB --> ReadDB: **replication**\n**<font color=red> (too late)**
Consumer--

@enduml