@startuml
title Temporal Expectations
hide footbox
skinparam monochrome reverse
participant P
participant "?"

P->B: M
B->C: M

hnote over "?": ⏱️
"?"->C: GET M\nExpecting done
@enduml
- chain an event back from C
