@startuml
title Request - Reply
hide footbox
skinparam monochrome reverse
->P
activate P
P->C: M
hnote over P: blocks\nfor reply
activate C
C->C: id=p(M)
C->P: ReplyM
deactivate C
P->P: after work (id)
<-P
deactivate P
@enduml
? how to connect reply with request
? what instance of P processes the Reply
? dynamic Rabbit queue
? when to use