@startuml
title Request - Reply via correlationId
hide footbox
skinparam monochrome reverse
->P:HTTP call
activate P
hnote over P: corrId=new UUID()
hnote over C: different dept\nof the bank
P-->C: RequestM{corrId}
hnote over P: blocks\nfor reply
activate C
C->C: id=process(RequestM)
C-->P: ReplyM{id,corrId}
deactivate C
hnote over P: more work
<-P
deactivate P
@enduml
? how to correlate ReplyM with RequestM
? what instance of P processes the Reply
? dynamic Rabbit queue
? when to use