@startuml
title Request - Resume
hide footbox
skinparam monochrome reverse
database DB order 9
participant C order 10

->P
activate P
P->DB: write workflow state{corrId, ts}
P-->C: RequestM
deactivate P
hnote over P: thread\nreleased
activate C
C->C: id=process(RequestM)
C-->P: ReplyM
deactivate C
activate P
P<-DB: read workflow state{corrId}
hnote over P: more work

alt no reply detected by a watchdog
P<-P: ??
note over P: usually devs forget
end
@enduml
? how to connect reply with request
? what instance of P receives the ReplyM
? "reply" or "event" from C