@startuml
title Request - Resume
hide footbox
database DB order 9
participant B order 10

->A
activate A
A->DB: write workflow state
A-->B: RequestM
deactivate A
hnote over A: thread\nreleased
activate B
B->B: r=process(RequestM)
B-->A: ReplyM{r}
deactivate B
activate A
A->DB: read workflow state
hnote over A: more work
@enduml
? how to connect reply with request
? what instance of A receives the ReplyM
? "reply" or "event" from B ?