@startuml
title Request - Reply
hide footbox
skinparam monochrome reverse
->P
activate P
P->C: RequestM
hnote over P: blocks\nfor reply
activate C
C->C: id=process(RequestM)
C->P: ReplyM
deactivate C
hnote over P: more work
<-P
deactivate P
@enduml
? how to correlate ReplyM with RequestM
? what instance of P processes the Reply
? dynamic Rabbit queue
? when to use