@startuml
title Request - Reply
hide footbox
skinparam monochrome reverse
->P
activate P
P->C: M{correlationId=uuid}
activate C
C->C: id=p(M)
C->P: ReplyM{correlationId=uuid}
deactivate C
P->P: after work (id)
<-P
deactivate P
@enduml

