@startuml
title Atomic Consume-Produce
hide footbox
participant Topic1
participant C

Topic1->C: M1
group transaction
    C->Topic1: Ack M1
    C->Topic2: Send M2
end
@enduml
- +Send M3 to Topic2/T3
- Receive M1b => stateful
- Kafka transaction (consume* + produce*)