@startuml
title Atomic Consume + SQL
hide footbox
skinparam monochrome reverse
participant B
participant C
database DB

B->C: M
group transaction
    C->DB: update(s)
    C->B: Ack M
end

@enduml
? inbox pattern
