@startuml
title Atomic Consume + SQL
hide footbox
participant B
participant C
database DB

B<-C: poll from consumer_offset
B->C: M
group transaction
    C->DB: update(s)
    C->DB: update consumer_offset
end

@enduml
? inbox pattern
