@startuml
title Atomic SQL + Produce
hide footbox
database SQL order 9
queue B order 10

group transaction
    P->SQL: update(s)
    P->B: Send M
end
@enduml
? transactional outbox pattern
? CDC/Debezium

