@startuml
title Atomic (SQL + Send)\nFix: CDC with Debezium/Kafka Connect
hide footbox
participant P
database SQL
participant Debezium
queue B

group transaction
    P->SQL: update(s)
end

Debezium->Debezium++:
group continuously
SQL<-Debezium:tail transaction log
Debezium->KafkaB:M (exactly once)
Debezium--
end

@enduml