@startuml
title Atomic SQL + Produce
hide footbox
skinparam monochrome reverse
database " " as DB order 9
participant B order 10

group transaction
    P->DB: update
    P->B: M
'    P->DB: insert M into OUTBOX
end

'Poller->DB: M = select from OUTBOX
'Poller->B: M
'Poller->DB: delete M from OUTBOX

'group CDC
'    DB->B: M
'end
@enduml

