@startuml
title Atomic Consume + SQL
hide footbox
skinparam monochrome reverse
participant B
participant C
database DB

group transaction
    B->C: M
    C->DB: insert M in INBOX
    C->B: Ack M
end
group CDC
    B->BC: M
end

group transaction
    Poller->DB: select M from INBOX
    C->C: process(M)
    C->DB: updates+
    Poller->DB: delete M from INBOX
end

@enduml

