@startuml
title Atomic SQL + Produce
hide footbox
database "Aerospike" as DB order 9
queue B order 10

alt tx
    P->DB: update(s)
    P->DB: insert into outbox M
end
Poller->DB: select M from outbox
Poller->B!!: Send M
@enduml
? transactional outbox pattern
? CDC/Debezium

"you never send a message before writing to the DB"
Because aerospike is more likely to fail