    @startuml
title Atomic Consume-Produce
hide footbox
skinparam monochrome reverse
participant B
participant C

group transaction
    B->C: M1part1
    B->C: M1part2
    C->B: AckM1
    C->B: M2
end
@enduml
- Send n*M2
- Receive n*M1 + stateful

