@startuml
title Atomic SQL + Produce
hide footbox
database " " as DB order 9
queue B order 10

group transaction
    P->DB: update(s)
    P->B: Send M
end
@enduml
? transactional outbox pattern
? CDC/Debezium

