@startuml
title Consumer Error Handling
hide footbox

P->C: M
alt
    loop retry 10x + timeout
        C->C!!: process(M)
    end
else catch (error)
    hnote over C: log.error("[ALARM-P1]M")

'    C->DLQ: M
'    hnote over DLQ: alarm\n±manual replay

'    C->B: PaymentFailedEvent
end

@enduml
