@startuml
title Poison Pill
hide footbox
participant B
participant C1

B->C1++: M
C1->API++:call
hnote over API: takes\n10+ min
C1<--API--
hnote over C1: no heartbeat\nsent on time
C1--
B->B: rebalance\npartition\nto C2\n(RIP C1)

@enduml
? inbox pattern
