@startuml
title Claim Check Pattern
hide footbox
skinparam monochrome reverse

P-->B: M {personId}
B-->C: M {personId}
C->P: GET /person{personId}
P->P.DB: write person data
note over P: GDPR !
@enduml
