@startuml
'title Consumer Callback Race vs Produce DB Replication
hide footbox
participant Producer
participant DB

-> Producer++:update
Producer -> DB++#lightgreen : UPDATE

'⭐️uncomment bellow, in chunks
'Producer --> Consumer++: UpdatedEvent {id}

'Consumer->Producer: GET /{id}   **// callback**

'Producer++
'Producer->DB++#pink: <font color=red> SELECT
'DB--
'Producer-->Consumer: <font color=red>  old data
'Producer--

Producer -> DB--: COMMIT
Producer--

@enduml