server.port=8085
spring.application.name=checkout
spring.kafka.bootstrap-servers=localhost:9092
management.health.kafka.enabled=false
management.health.binders.enabled=false
member.service.url=http://localhost:8082
teleport.service.url=http://localhost:8083
